# fly.toml app configuration file generated for movierecs on 2025-06-24T12:05:14-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movierecs'
primary_region = 'den'

[build]

[build.args]
  VITE_API_URL = "https://movie-recommender-fragrant-shape-7289.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
